### ISSUE TITLE
API_KEY formatting

### ISSUE THREAD

**Issue by pickleton89** [AnswerDotAI/shell_sage#10]
In my terminal I need to have parentheses around the actual API key. You just list the API key after the export ANTHROPIC_API_KEY=api_key

I think it would be clearer for novices to have
ANTHROPIC_API_KEY="api_key"

All the best.

**Comment by ncoop57** [comment]
That's interesting, what terminal are you using? All unix based shells should support the export syntax shown in the readme.

**Comment by pickleton89** [comment]
I was using iTerm.

**Comment by ncoop57** [comment]
Hmm yeah not sure why it wasn't working for you. I have no issues running it in iterm. I'm gonna go ahead and close this.
