### ISSUE TITLE
--NH flag: does it work?

### ISSUE THREAD

**Issue by aborruso** [AnswerDotAI/shell_sage#19]
Hi,
I have read [here](https://www.answer.ai/posts/2024-12-05-introducing-shell-sage.html) about this flag.

But if I use it, it does not work

```
ssage --NH "what are the man flags for tar?"
usage: ssage [-h] [--pid PID] [--skip_system] [--history_lines HISTORY_LINES] [--s] [--c] [--provider PROVIDER] [--model MODEL] [--base_url BASE_URL] [--api_key API_KEY] [--code_theme CODE_THEME] [--code_lexer CODE_LEXER] [--verbosity VERBOSITY] query [query ...]
ssage: error: unrecognized arguments: --NH
```

Thank you

**Comment by ncoop57** [comment]
Ah good catch, we no longer use this flag as we auto detect if you are in a tmux session.

**Comment by ncoop57** [comment]
Is this flag something you find yourself needing still @aborruso ?

**Comment by aborruso** [comment]
> Ah good catch, we no longer use this flag as we auto detect if you are in a tmux session.

@ncoop57  If I run `ssage "what are the man flags for tar?"` inside tmux, it works.
If I run it outside tmux I have the below error

![image](https://github.com/user-attachments/assets/d9ff5213-02b2-4c2d-a74b-46f426860302)

**Comment by ncoop57** [comment]
What version of shell sage are you using @aborruso ?

**Comment by aborruso** [comment]
> What version of shell sage are you using @aborruso ?

How to know it? Is there a `--version` option?

I have installed in these days, using `uv tool install --python 3.11 shell_sage`

**Comment by aborruso** [comment]
If I run `uv tool upgrade shell_sage`                                                                                                                                                                             

I have `Nothing to upgrade`

**Comment by ncoop57** [comment]
hmmmm, seems like you are using the most recent. What shell are you using?

**Comment by ncoop57** [comment]
Also, I don't have a `--version` flag, but that would be a good thing to add! I'll go ahead and make a commit to have it included in the next release

**Comment by ncoop57** [comment]
Hmmmm, interesting. What operating system are you using? Can you run this command and tell me what it outputs? `echo $TMUX`

**Comment by aborruso** [comment]
> Hmmmm, interesting. What operating system are you using? Can you run this command and tell me what it outputs? `echo $TMUX`

Hi it's empty.

My OS (I'm using it, inside WSL)

```
cat /etc/debian_version
12.5
```

**Comment by aborruso** [comment]
> Hmmmm, interesting. What operating system are you using? Can you run this command and tell me what it outputs? `echo $TMUX`

Inside `tmux` I have

```
echo $TMUX
/tmp/tmux-1000/default,222889,0
```

**Comment by ncoop57** [comment]
That's so weird... It is empty for me outside of tmux too which is what we check for, so I'm not sure why it is causing issues with your installation 🤔

**Comment by aborruso** [comment]
> That's so weird... It is empty for me outside of tmux too which is what we check for, so I'm not sure why it is causing issues with your installation 🤔

What about to add it as option, for all the strange cases like mine where it is not automatically mapped properly?

**Comment by ncoop57** [comment]
Yeah, that should fix this issue. Though I think there should be a way to automatically detect it. I'll look more into it and if I can't figure it out, I'll add the flag back for these cases (btw I was able to reproduce locally after a few uninstalls and reinstalls)

**Comment by ncoop57** [comment]
Ahh I figured out the issue. I had added a new feature that automatically detects the scroll back history of tmux, but I did not first check that tmux is available before running that check. Fixing now. Thanks for helping find this!

**Comment by aborruso** [comment]
> Ahh I figured out the issue. I had added a new feature that automatically detects the scroll back history of tmux, but I did not first check that tmux is available before running that check. Fixing now. Thanks for helping find this!

Thank you very much

**Comment by ncoop57** [comment]
okay, fixed in main! Will be included in the next pypi release, but should be stable to install directly from the git repo 🤓

**Comment by aborruso** [comment]
> okay, fixed in main! Will be included in the next pypi release, but should be stable to install directly from the git repo 🤓

I will wait for it. Thank you very much
