### ISSUE TITLE
Slow Reaction times

### ISSUE THREAD

**Issue by Overlytic** [AnswerDotAI/shell_sage#3]
I am having slow reactions times when running shell_sage. For instance:

```
$ time ssage "hello"
Hello! I'm ShellSage, your command-line teaching assistant. How can I help you with shell commands or system administration today? Feel free to ask any questions about
specific commands, scripting, or general Linux/Unix topics.

real    0m22.498s
user    0m1.176s
sys     0m1.647s
```

I tried using no-history mode to see if that would increase the speed. There was no difference. 

```
$ time ssage "hello" --NH
Hello! I'm ShellSage, your command-line teaching assistant. How can I help you with shell commands or system administration today? Feel free to ask about specific commands,
file operations, or any other command-line related topics.

real    0m23.145s
user    0m1.176s
sys     0m2.114s
```

I am wondering if it could be possible to add a command-line option to show the different causes of latency for the command (i.e. how long it takes till a query is sent to claude, how long it takes to respond), to make it easier to debug such cases.

**Comment by Isaac-Flath** [comment]
[Adding a verbosity flag to get timestamps of steps](https://github.com/AnswerDotAI/shell_sage/pull/5)

**Comment by ncoop57** [comment]
Closing this for now since we now have a verbosity flag thanks to @Isaac-Flath !
