### ISSUE TITLE
The file nbs/index.ipynb does not exist.

### ISSUE THREAD

**Issue by tomaslucas** [AnswerDotAI/shell_sage#7]
Reading the `CONTRIBUTING.md` file we can read, under the Updating `README.md` section, the next:
Then, after you make subsequent changes to `nbs/index.ipynb`, run the following from the repo's root directory to (re)build `README.md`

But there is no `nbs/index.ipynb` file in that folder.

![image](https://github.com/user-attachments/assets/86e3c5c7-df08-49da-8be1-1d1f29ee60c8)

**Comment by ncoop57** [comment]
Ah yes, thank you! I will update the repo to have an index.ipynb in a bit. For now, readme changes can be made directly to the readme.md. Sorry for the confusion!
