### ISSUE TITLE
Groq Api

### ISSUE THREAD

**Issue by aborruso** [AnswerDotAI/shell_sage#9]
Hello and thank you for this wonderful project. 

Is it possible to use also the [groq API](https://console.groq.com/docs/openai), which is openai compatible?

Thank you

**Comment by ncoop57** [comment]
This is now supported from main

**Comment by aborruso** [comment]
Thank you very much

**Comment by aborruso** [comment]
hi @ncoop57 how to set it?

I have set in this way my config file:

```
[DEFAULT]
provider = openai
model = llama-3.3-70b-versatile
base_url = https://api.groq.com/openai/v1
api_key = xxxxxx
history_lines = -1
code_theme = monokai
code_lexer = python
```

When I run `ssage hi ShellSage` I get

```
raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "property 'max_completion_tokens' is unsupported, did you mean 'max_tokens'?", 'type': 'invalid_request_error'}}
```

Thank you

**Comment by ncoop57** [comment]
@aborruso 

Weird... it looks like Groq does not follow the openai api spec properly: https://platform.openai.com/docs/api-reference/chat/create#chat-create-max_completion_tokens

Gonna go ahead and close this as this is a problem with Groq and not shell sage

**Comment by aborruso** [comment]
Thank you @ncoop57 

> Gonna go ahead and close this as this is a problem with Groq and not shell sage

I have seen that groq uses max_tokens and it is Deprecated :(
